alipay_django/alipay_django225/urls.py
from django.contrib import admin
from django.urls import path
from demo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('goods/', views.goods, name='goods'),
    path('purchase/<int:goods_id>/', views.purchase, name='purchase'),
    path('show_msg/', views.show_msg, name='show_msg'),
    path('check_order/', views.check_order, name='check_order'),
    path('order_list/', views.order_list, name='order_list'),
]

alipay_django/demo/models.py
from django.db import models

# Create your models here.


class Goods(models.Model):
    """商品"""
    goods_name = models.CharField(max_length=100, verbose_name='商品名称')
    goods_price = models.FloatField(default=0.0, verbose_name='商品价格')

    class Meta:
        verbose_name = "商品"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.goods_name


class Order(models.Model):
    """订单信息"""
    ORDER_STATUS = (
        (0, "未支付"),
        (1, "已支付"),
    )

    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='商品名字')
    order_num = models.CharField(max_length=64, verbose_name='订单序号')
    order_status = models.IntegerField(choices=ORDER_STATUS, default=0)

    class Meta:
        verbose_name = "订单信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}: {}".format(self.goods.goods_name, self.order_num)

alipay_django/demo/views.py
import uuid
from urllib.parse import parse_qs
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from demo.models import Goods, Order
from utils.pay_api import AliPay
from alipay_django225.settings import private_key_path, ali_pub_key_path

# Create your views here.


def goods(request):
    goods_list = Goods.objects.all()
    context = {
        'goods_list': goods_list,
    }
    
    return render(request, 'demo/goods.html', context)


def purchase(request, goods_id):
    """
    订单支付
    :param request:
    :param goods_id:
    :return:跳转到支付宝订单页面
    """
    # 获取商品信息，因为向支付宝接口发送请求的时候需要携带该商品相关信息
    obj_goods = Goods.objects.filter(pk=goods_id)[0]
    '''
    生成订单
    '''
    order_number = str(uuid.uuid4())
    Order.objects.create(
        order_num=order_number,
        goods=obj_goods,
    )
    '''
    跳转到支付宝页面
    '''
    alipay = AliPay(
        appid='2016092500591336',
        app_notify_url=' ',
        return_url=' ',
        app_private_key_path=private_key_path,      # 应用私钥
        alipay_public_key_path=ali_pub_key_path,    # 支付宝公钥
        debug=True
    )

    query_params = alipay.direct_pay(
        subject=obj_goods.goods_name,
        out_trade_no=order_number,
        total_amount=obj_goods.goods_price,
    )

    pay_url = 'https://openapi.alipaydev.com/gateway.do?{0}'.format(query_params)
    return redirect(pay_url)


def show_msg(request):
    if request.method == "GET":
        alipay = AliPay(
            appid='2016092500591336',
            app_notify_url='127.0.0.1:8000/check_order/',
            return_url='127.0.0.1:8000/show_msg/',
            app_private_key_path=private_key_path,  # 应用私钥
            alipay_public_key_path=ali_pub_key_path,  # 支付宝公钥
            debug=True
        )
        params = request.GET.dict()     # 获取请求携带的参数并转换成字典类型
        print(request.GET)
        print(params)
        sign = params.pop('sign', None)     # 获取sign值
        # 对sign进行验证
        status = alipay.verify(params, sign)
        if status:
            return render(request, 'demo/show_msg.html', {'msg': '支付成功'})
        else:
            return render(request, 'demo/show_msg.html', {'msg': '支付失败'})
    else:
        return render(request, 'demo/show_msg.html', {'msg': '只支持GET请求，不支持其他请求。'})


@csrf_exempt
def check_order(request):
    """
    支付宝通知支付的结果信息，如果支付成功可以用来修改订单的状态
    :param request:
    :return:
    """
    if request.method == "POST":
        alipay = AliPay(
            appid='2016092500591336',
            app_notify_url='http://106.12.115.136:8000//check_order/',
            return_url='127.0.0.1:8000/show_msg/',
            app_private_key_path=private_key_path,  # 应用私钥
            alipay_public_key_path=ali_pub_key_path,  # 支付宝公钥
            debug=True
        )
        body_str = request.body.decode("utf-8")
        post_data = parse_qs(body_str)  # 根据&符号分割
        print(post_data)
        post_dict = {}
        for k, v in post_data.items():
            post_dict[k] = v[0]
        sign = post_dict.pop('sign', '')
        status = alipay.verify(post_dict, sign)
        if status:
            out_trade_no = post_data['out_trade_no']
            Order.objects.filter(order_num=out_trade_no).update(order_status=1)
            return HttpResponse("success")
        else:
            return HttpResponse("支付失败")
    else:
        return HttpResponse("只支持POST请求")


def order_list(request):
    order_obj = Order.objects.all()
    context = {
        'order_obj': order_obj,
    }
    
    return render(request, "demo/order_list.html", context)

alipay_django/demo/templates/demo/goods.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
     content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>商品信息</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
     integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <div class="row" style="margin-top: 10px">
    <h4 style="text-align: center;font-weight: bold">Django支付宝支付案例</h4>
  </div>
  <div class="row" style="margin-top: 10px">
    <div class="col-md-4 col-md-offset-4">
      <table class="table table-bordered">
        {% for row in goods_list %}
          <tr style="text-align: center">
            <td>{{ row.id }}</td>
            <td>{{ row.goods_name }}</td>
            <td>{{ row.goods_price }}</td>
            <td><a href="{% url "purchase" row.id %}">购买</a></td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
<div class="container-fluid" style="color: #b2bcc5;margin-top: 20px;margin-bottom: 2px">
  <div class="row">
    <div class="col-md-12 text-center" style="padding: 40px">
      Copyright © 2019-2020 非马梦衢 版权所有
      <a target="_blank_" href="http://www.miit.gov.cn/" style="color:#b2bcc5;">豫ICP备19014367号-1</a>
    </div>
  </div>
</div>
</body>>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>
</html>

alipay_django/demo/templates/demo/order_list.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
     content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>订单信息</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
     integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <div class="row" style="margin-top: 10px">
    <h4 style="text-align: center;font-weight: bold">Django支付宝支付案例</h4>
  </div>
  <div class="row" style="margin-top: 10px">
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-bordered">
        <tr style="text-align: center">
          <th style="text-align: center">订单ID</th>
          <th style="text-align: center">订单号</th>
          <th style="text-align: center">订单状态</th>
          <th style="text-align: center">商品名称</th>
          <th style="text-align: center">商品价格</th>
        </tr>
        {% for row in order_obj %}
          <tr style="text-align: center">
            <td>{{ row.id }}</td>
            <td>{{ row.order_number }}</td>
            <td>{{ row.get_order_status_display }}</td>
            <td>{{ row.goods.goods_name }}</td>
            <td>{{ row.goods.goods_price }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
<div class="container-fluid" style="color: #b2bcc5;margin-top: 20px;margin-bottom: 2px">
  <div class="row">
    <div class="col-md-12 text-center" style="padding: 40px">
      Copyright © 2019-2020 非马梦衢 版权所有
      <a target="_blank_" href="http://www.miit.gov.cn/" style="color:#b2bcc5;">豫ICP备19014367号-1</a>
    </div>
  </div>
</div>
</body>
</html>

alipay_django/demo/templates/demo/show_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>支付结果</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
     integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"">
</head>
<body>
    <div class="container">
        <div class="row" style="margin-top: 30px">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-primary">
                    <div class="panel-body text-center">{{ msg }}!</div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>